language: swift
osx_image: xcode11
xcode_project: Macduff.xcodeproj
xcode_scheme: AppForTest
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone XÊ€

cache:
  bundler: true
  directories:
    - Carthage
  
before_install:
  - carthage bootstrap --cache-builds

after_success:
  - slather